name: Run Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  run-tests:
    name: "Test (${{ matrix.arch }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ["x86", "x86_64"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Run setup-libraries composite action
      uses: ./lib_ass/src/main/cpp/libass-cmake/.github/actions/setup-libraries
      with:
        libass-cmake-path: ${{ github.workspace }}/lib_ass/src/main/cpp/libass-cmake

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 21
        arch: ${{ matrix.arch }}
        script: ./gradlew test connectedAndroidTest
